server:
  port: 9001

spring:
  application:
    name: study-ribbon

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

ribbon:
  ConnectTimeout: 3000