server:
  port: 9000

spring:
  application:
    name: study-hystrix

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


hystrix:
  command:
    default:
      execution:
        timeoutInMilliseconds: 10000
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 5000
